### ISSUE TITLE
Word search broken

### ISSUE THREAD

**Issue by mohaballi** [em-gazelle/search_process_save_images#1]
Error upon submitting word search:

<img width="1107" alt="screen shot 2018-05-03 at 4 25 23 pm" src="https://user-images.githubusercontent.com/981517/39601038-aa89e1e0-4eee-11e8-96de-df7e4ea2e855.png">

**Comment by em-gazelle** [comment]
Initially, the temporary images being saved in the 'temporary_uploads' directory were excluded via the .gitignore file. Although the directory itself was not explicitly ignored, the directory name was neither saved nor uploaded to Github without a placeholder image--and hence the error.

The first commit uploads a placeholder image to correct the error, and the second implements a better approach to processing and displaying temporary images by foregoing saving them to the application altogether.
